/**:
  ros__parameters:
    control_parameters:
        frequency: 20.0
        N: 50
        v_max: 1.5
        w_max: 1.0
        Q: [5.0, 5.0, 1.0]
        R: [0.2, 0.3]
        R_delta: [30.0, 50.0]
        Qf_factor: 15.0
    