/**:
  ros__parameters:
    control_parameters:
        frequency: 10.0
        N: 25
        v_max: 2.2
        w_max: 1.0
        Q: [5.0, 5.0, 1.0]
        R: [0.25, 0.15]
        R_delta: [30.0, 50.0]
        Qf_factor: 15.0
    
