/**:
  ros__parameters:
    mission:
      type: "racetrack_capsule"        # "line_to" | "straight" | "arc" | "rounded_rectangle" | "racetrack_capsule"
      common:
        repeat: "loop"                 # "none" | "loop" | "pingpong"
        # start pose handling: either use current pose or set an absolute start
        start:
          use_current: true            # if false, use x/y/psi below
          x: 0.0
          y: 0.0
          psi: 0.0
        speed: 0.5                     # common cruise speed (ignored for some types)
      params:
        # For line_to:
        # goal_xypsi: [6.0, 0.5, 0.0]
        # duration: 100.0

        # For straight:
        # segment_distance: 10.0       # 0 => unbounded

        # For arc:
        # radius: 3.0
        # angle: 1.57079632679         # optional if yaw_rate given
        # yaw_rate: 0.4                # optional if angle given
        # cw: true

        # For rounded_rectangle:
        # width: 10.0
        # height: 6.0
        # corner_radius: 1.0
        # cw: true

        # For racetrack_capsule:
        straight_length: 12.0
        radius: 5.0
        cw: true